export const gridData = {
  fileSystemColumns: [
    { field: "NO", title: "NO", width: "30", className: "no" },
    { field: "SERVICE", title: "서비스", width: "120", className: "service" },
    {
      field: "SERVERNAME",
      title: "장비명",
      width: "120",
      className: "servername",
    },
    { field: "UTILIZATION", title: "사용률(%)", className: "utilization" },
  ],
  serverColumns: [
    { field: "NO", title: "NO", width: "30", className: "no" },
    {
      field: "SERVERNAME",
      title: "장비명",
      width: "160",
      className: "servername",
    },
    { field: "UTILIZATION", title: "사용률(%)", className: "utilization" },
  ],
  alarmColumns: [
    {
      field: "ALARMSEVERITY",
      title: "등급",
      width: "40",
      className: "alarmseverity",
    },
    { field: "TIME", title: "발생일시", width: "160", className: "time" },
    {
      field: "ALARMSERVERNAME",
      title: "장비명",
      width: "220",
      className: "alarmservername",
    },
    {
      field: "IP",
      title: "ip",
      width: "120",
      className: "ip",
    },
    {
      field: "RESOURCENAME",
      title: "리소스명",
      width: "270",
      className: "resourcename",
    },
    {
      field: "ALARMNAME",
      title: "알람명",
      width: "320",
      className: "alarmname",
    },
    {
      field: "DETAIL",
      title: "상세내용",
      className: "detail",
    },
  ],
  Rank_file_data: [
    {
      NO: "1",
      SERVICE: "운영망",
      SERVERNAME: "운영망",
      UTILIZATION: 83.3,
    },
    {
      NO: "2",
      SERVICE: "전송망",
      SERVERNAME: "전송망",
      UTILIZATION: 82,
    },
    {
      NO: "3",
      SERVICE: "UPS",
      SERVERNAME: "UPS",
      UTILIZATION: 65.2,
    },
    {
      NO: "4",
      SERVICE: "네트워크망",
      SERVERNAME: "네트워크망",
      UTILIZATION: 20.3,
    },
    {
      NO: "5",
      SERVICE: "일반망",
      SERVERNAME: "일반망",
      UTILIZATION: 10.4,
    },
  ],
  Rank_server_data: [
    {
      NO: "1",
      SERVERNAME: "mbv-onwas6",
      UTILIZATION: 83.3,
    },
    {
      NO: "2",
      SERVERNAME: "mbv-cpndb",
      UTILIZATION: 82,
    },
    {
      NO: "3",
      SERVERNAME: "mbv-emsdp",
      UTILIZATION: 65.2,
    },
    {
      NO: "4",
      SERVERNAME: "mbv-onwas3",
      UTILIZATION: 20.3,
    },
    {
      NO: "5",
      SERVERNAME: "mbv-emsap",
      UTILIZATION: 10.4,
    },
  ],
  AlarmData: [
    {
      ALARMSEVERITY: "심각",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "Polestar-AP2",
      IP: "192.168.232.12",
      RESOURCENAME: "CPU",
      ALARMNAME: "프로세스 메모리 사용률 비교(베이스라인)",
      DETAIL: "WIN NetworkConfig_Applinfo(EventLog감시)log메세지 Critical 발생",
    },
    {
      ALARMSEVERITY: "심각",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "S4048-BB2",
      IP: "192.168.232.12",
      RESOURCENAME: "Vlan2",
      ALARMNAME: "포트",
      DETAIL: "가용성 [DOWN(=DOWN,2회 연속)]",
    },
    {
      ALARMSEVERITY: "경고",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "S4048-BB2",
      IP: "192.168.232.12",
      RESOURCENAME: "ManagementEthernet 1/1",
      ALARMNAME: "포트",
      DETAIL: "가용성 [DOWN(=DOWN,2회 연속)]",
    },
    {
      ALARMSEVERITY: "경고",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "S4048-BB2",
      IP: "192.168.232.12",
      RESOURCENAME: "TenGigabitEthernet 1/45",
      ALARMNAME: "응답시간",
      DETAIL: "업무서비스 응답시간 지연[2.0ms(>0.1ms, 2회 연속)]",
    },
    {
      ALARMSEVERITY: "심각",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "S4048-BB2",
      IP: "192.168.232.12",
      RESOURCENAME: "TenGigabitEthernet 1/45",
      ALARMNAME: "응답시간",
      DETAIL: "업무서비스 응답시간 지연[2.0ms(>0.1ms, 2회 연속)]",
    },
    {
      ALARMSEVERITY: "경고",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "S4048-BB2",
      IP: "192.168.232.12",
      RESOURCENAME: "TenGigabitEthernet 1/45",
      ALARMNAME: "응답시간",
      DETAIL: "업무서비스 응답시간 지연[2.0ms(>0.1ms, 2회 연속)]",
    },
    {
      ALARMSEVERITY: "심각",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "S4048-BB2",
      IP: "192.168.232.12",
      RESOURCENAME: "TenGigabitEthernet 1/45",
      ALARMNAME: "응답시간",
      DETAIL: "업무서비스 응답시간 지연[2.0ms(>0.1ms, 2회 연속)]",
    },
    {
      ALARMSEVERITY: "경고",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "S4048-BB2",
      IP: "192.168.232.12",
      RESOURCENAME: "TenGigabitEthernet 1/45",
      ALARMNAME: "응답시간",
      DETAIL: "업무서비스 응답시간 지연[2.0ms(>0.1ms, 2회 연속)]",
    },
    {
      ALARMSEVERITY: "심각",
      TIME: "2021/06/24 09: 00: 05",
      ALARMSERVERNAME: "S4048-BB2",
      IP: "192.168.232.12",
      RESOURCENAME: "TenGigabitEthernet 1/45",
      ALARMNAME: "응답시간",
      DETAIL: "업무서비스 응답시간 지연[2.0ms(>0.1ms, 2회 연속)]",
    },
  ],
  columnChartGroupData: [
    {
      RESOURCE_ID: 1,
      RESOURCE_NAME: "COLUMN",
      RESOURCE_GROUP_LIST: [
        {
          GROUP_ID: 1,
          GROUP_NAME: "/root",
          DATA: 100,
        },
        {
          GROUP_ID: 2,
          GROUP_NAME: "user",
          DATA: 80,
        },
        {
          GROUP_ID: 3,
          GROUP_NAME: "etc",
          DATA: 70,
        },
        {
          GROUP_ID: 4,
          GROUP_NAME: "bar",
          DATA: 60,
        },
        {
          GROUP_ID: 5,
          GROUP_NAME: "/tmp",
          DATA: 60,
        },
      ],
    },
  ],
};
